import 'products.dart';

class MyProducts {
  static List<Product> allProducts = [
    Product(
        onSale: true,
        id: 1,
        name: 'IPhone 13 Pro',
        category: 'phones',
        image: 'assets/images/products/phones/iphone1.jpg',
        description: 'lorem ipsum',
        price: '18.999.000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Iqoo 12 5G',
        category: 'phones',
        image: 'assets/images/products/phones/iqoo1.jpg',
        description: 'lorem ipsum',
        price: '16,000,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Samsung S23 5G',
        category: 'phones',
        image: 'assets/images/products/phones/samsung1.jpg',
        description: 'lorem ipsum',
        price: '17,000,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'SONY PS5',
        category: 'consoles',
        image: 'assets/images/products/consoles/playstation1.jpg',
        description: 'lorem ipsum',
        price: '10,000,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'SONY PS4',
        category: 'consoles',
        image: 'assets/images/products/consoles/playstation2.jpg',
        description: 'lorem ipsum',
        price: '8,500,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Asus TUF Gaming',
        category: 'laptops',
        image: 'assets/images/products/laptops/asus1.jpg',
        description: 'lorem ipsum',
        price: '19,000,000'),
    Product(
        onSale: true,
        id: 1,
        name: 'Lenovo Legion Pro',
        category: 'laptops',
        image: 'assets/images/products/laptops/laptop1.jpg',
        description: 'lorem ipsum',
        price: '18,900,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Apple Macbook 2023',
        category: 'laptops',
        image: 'assets/images/products/laptops/macbook1.jpg',
        description: 'lorem ipsum',
        price: '22,000,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Nikon DSLR',
        category: 'camera',
        image: 'assets/images/products/camera/nikon1.jpg',
        description: 'lorem ipsum',
        price: '8,500,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Airpods Pro Max',
        category: 'audio',
        image: 'assets/images/products/headphones/airpod1.jpg',
        description: 'lorem ipsum',
        price: '9.500.000'),
    Product(
        onSale: false,
        id: 1,
        name: 'JBL ANC76',
        category: 'audio',
        image: 'assets/images/products/headphones/jbl1.jpg',
        description: 'lorem ipsum',
        price: '1,500,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Sony KB250',
        category: 'audio',
        image: 'assets/images/products/headphones/sony1.jpg',
        description: 'lorem ipsum',
        price: '2,200,00'),
    Product(
        onSale: false,
        id: 1,
        name: 'GTA 5 - PS4',
        category: 'games',
        image: 'assets/images/products/games/gta5.jpg',
        description: 'lorem ipsum',
        price: '450,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Fifa- PS4',
        category: 'games',
        image: 'assets/images/products/games/fifa22.jpg',
        description: 'lorem ipsum',
        price: '234,000'),
  ];
  static List<Product> phonesList = [
    Product(
        onSale: true,
        id: 1,
        name: 'IPhone 13 Pro',
        category: 'phones',
        image: 'assets/images/products/phones/iphone1.jpg',
        description: 'lorem ipsum',
        price: '18,999.000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Iqoo 12 5G',
        category: 'phones',
        image: 'assets/images/products/phones/iqoo1.jpg',
        description: 'lorem ipsum',
        price: '5,650,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Samsung S23 5G',
        category: 'phones',
        image: 'assets/images/products/phones/samsung1.jpg',
        description: 'lorem ipsum',
        price: '17,089,00'),
  ];
  static List<Product> consoleList = [
    Product(
        onSale: false,
        id: 1,
        name: 'SONY PS5',
        category: 'consoles',
        image: 'assets/images/products/consoles/playstation1.jpg',
        description: 'lorem ipsum',
        price: '10,876,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'SONY PS4',
        category: 'consoles',
        image: 'assets/images/products/consoles/playstation2.jpg',
        description: 'lorem ipsum',
        price: '8,867,000'),
  ];
  static List<Product> laptopList = [
    Product(
        onSale: false,
        id: 1,
        name: 'Asus TUF Gaming',
        category: 'laptops',
        image: 'assets/images/products/laptops/asus1.jpg',
        description: 'lorem ipsum',
        price: '18,765,000'),
    Product(
        onSale: true,
        id: 1,
        name: 'Lenovo Legion Pro',
        category: 'laptops',
        image: 'assets/images/products/laptops/laptop1.jpg',
        description: 'lorem ipsum',
        price: '23,650,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Apple Macbook 2023',
        category: 'laptops',
        image: 'assets/images/products/laptops/macbook1.jpg',
        description: 'lorem ipsum',
        price: '22,564,00'),
  ];
  static List<Product> cameraList = [
    Product(
        onSale: false,
        id: 1,
        name: 'Nikon DSLR',
        category: 'camera',
        image: 'assets/images/products/camera/nikon1.jpg',
        description: 'lorem ipsum',
        price: '5,650,000'),
  ];
  static List<Product> audioList = [
    Product(
        onSale: true,
        id: 1,
        name: 'Airpods Pro Max',
        category: 'audio',
        image: 'assets/images/products/headphones/airpod1.jpg',
        description: 'lorem ipsum',
        price: '8,650,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'JBL ANC76',
        category: 'audio',
        image: 'assets/images/products/headphones/jbl1.jpg',
        description: 'lorem ipsum',
        price: '1,567,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Sony KB250',
        category: 'audio',
        image: 'assets/images/products/headphones/sony1.jpg',
        description: 'lorem ipsum',
        price: '2,100,000'),
  ];
  static List<Product> gamesList = [
    Product(
        onSale: false,
        id: 1,
        name: 'GTA 5 - PS4',
        category: 'games',
        image: 'assets/images/products/games/gta5.jpg',
        description: 'lorem ipsum',
        price: '432,000'),
    Product(
        onSale: false,
        id: 1,
        name: 'Fifa- PS4',
        category: 'games',
        image: 'assets/images/products/games/fifa22.jpg',
        description: 'lorem ipsum',
        price: '249,000'),
  ];
  static List<Product> saleProducts = [
    Product(
        onSale: true,
        id: 1,
        name: 'IPhone 13 Pro',
        category: 'phones',
        image: 'assets/images/products/phones/iphone1.jpg',
        description: 'lorem ipsum',
        price: '18,999,000'),
    Product(
        onSale: true,
        id: 1,
        name: 'Lenovo Legion Pro',
        category: 'laptops',
        image: 'assets/images/products/laptops/laptop1.jpg',
        description: 'lorem ipsum',
        price: '22,865,000'),
    Product(
        onSale: true,
        id: 1,
        name: 'Airpods Pro Max',
        category: 'audio',
        image: 'assets/images/products/headphones/airpod1.jpg',
        description: 'lorem ipsum',
        price: '12,876,000'),
  ];
}
